### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by tombarys** [dive2Pro/roam-preview-panels#1]
Hi, the preview is great addition but shows too much often when just accidentally hovering over page links when working with Roam. Some setting for delay to lag showing the preview would be great. :)

**Comment by dive2Pro** [comment]
Yes, good idea. It will be supported in the next version

**Comment by dive2Pro** [comment]
The new version is now online, please update it.

**Comment by tombarys** [comment]
Great, thanks!
—
Reply to this email directly, view it on GitHub
<https://github.com/dive2Pro/roam-preview-panels/issues/1#event-
7809608390>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABLWYSHQKC2PTNSURGRFKYLWILTR3ANCNFSM6AAAAAAR53A3UM>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
